// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: faceitmate.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWatchingResponse_ResponseCode int32

const (
	RegisterWatchingResponse_SUCCESS             RegisterWatchingResponse_ResponseCode = 0
	RegisterWatchingResponse_FAILURE             RegisterWatchingResponse_ResponseCode = 1
	RegisterWatchingResponse_NOT_FOUND           RegisterWatchingResponse_ResponseCode = 2
	RegisterWatchingResponse_FACEIT_NOT_RESPONSE RegisterWatchingResponse_ResponseCode = 3
)

// Enum value maps for RegisterWatchingResponse_ResponseCode.
var (
	RegisterWatchingResponse_ResponseCode_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
		2: "NOT_FOUND",
		3: "FACEIT_NOT_RESPONSE",
	}
	RegisterWatchingResponse_ResponseCode_value = map[string]int32{
		"SUCCESS":             0,
		"FAILURE":             1,
		"NOT_FOUND":           2,
		"FACEIT_NOT_RESPONSE": 3,
	}
)

func (x RegisterWatchingResponse_ResponseCode) Enum() *RegisterWatchingResponse_ResponseCode {
	p := new(RegisterWatchingResponse_ResponseCode)
	*p = x
	return p
}

func (x RegisterWatchingResponse_ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterWatchingResponse_ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_faceitmate_proto_enumTypes[0].Descriptor()
}

func (RegisterWatchingResponse_ResponseCode) Type() protoreflect.EnumType {
	return &file_faceitmate_proto_enumTypes[0]
}

func (x RegisterWatchingResponse_ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterWatchingResponse_ResponseCode.Descriptor instead.
func (RegisterWatchingResponse_ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_faceitmate_proto_rawDescGZIP(), []int{1, 0}
}

type RegisterPlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *RegisterPlayerRequest) Reset() {
	*x = RegisterPlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faceitmate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPlayerRequest) ProtoMessage() {}

func (x *RegisterPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faceitmate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPlayerRequest.ProtoReflect.Descriptor instead.
func (*RegisterPlayerRequest) Descriptor() ([]byte, []int) {
	return file_faceitmate_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPlayerRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterWatchingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseCode RegisterWatchingResponse_ResponseCode `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3,enum=api.RegisterWatchingResponse_ResponseCode" json:"response_code,omitempty"`
	Message      string                                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PlayerId     string                                `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *RegisterWatchingResponse) Reset() {
	*x = RegisterWatchingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faceitmate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterWatchingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWatchingResponse) ProtoMessage() {}

func (x *RegisterWatchingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faceitmate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWatchingResponse.ProtoReflect.Descriptor instead.
func (*RegisterWatchingResponse) Descriptor() ([]byte, []int) {
	return file_faceitmate_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWatchingResponse) GetResponseCode() RegisterWatchingResponse_ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return RegisterWatchingResponse_SUCCESS
}

func (x *RegisterWatchingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterWatchingResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_faceitmate_proto protoreflect.FileDescriptor

var file_faceitmate_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x61, 0x63, 0x65, 0x69, 0x74, 0x6d, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x33, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xf4, 0x01, 0x0a,
	0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0d, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x50, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e,
	0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x41,
	0x43, 0x45, 0x49, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53,
	0x45, 0x10, 0x03, 0x32, 0x56, 0x0a, 0x0a, 0x46, 0x61, 0x63, 0x65, 0x69, 0x74, 0x6d, 0x61, 0x74,
	0x65, 0x12, 0x48, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76, 0x64, 0x61, 0x6d,
	0x6d, 0x69, 0x74, 0x2f, 0x66, 0x61, 0x63, 0x65, 0x69, 0x74, 0x6d, 0x61, 0x74, 0x65, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faceitmate_proto_rawDescOnce sync.Once
	file_faceitmate_proto_rawDescData = file_faceitmate_proto_rawDesc
)

func file_faceitmate_proto_rawDescGZIP() []byte {
	file_faceitmate_proto_rawDescOnce.Do(func() {
		file_faceitmate_proto_rawDescData = protoimpl.X.CompressGZIP(file_faceitmate_proto_rawDescData)
	})
	return file_faceitmate_proto_rawDescData
}

var file_faceitmate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_faceitmate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_faceitmate_proto_goTypes = []interface{}{
	(RegisterWatchingResponse_ResponseCode)(0), // 0: api.RegisterWatchingResponse.ResponseCode
	(*RegisterPlayerRequest)(nil),              // 1: api.RegisterPlayerRequest
	(*RegisterWatchingResponse)(nil),           // 2: api.RegisterWatchingResponse
}
var file_faceitmate_proto_depIdxs = []int32{
	0, // 0: api.RegisterWatchingResponse.response_code:type_name -> api.RegisterWatchingResponse.ResponseCode
	1, // 1: api.Faceitmate.AddPlayer:input_type -> api.RegisterPlayerRequest
	2, // 2: api.Faceitmate.AddPlayer:output_type -> api.RegisterWatchingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_faceitmate_proto_init() }
func file_faceitmate_proto_init() {
	if File_faceitmate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_faceitmate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faceitmate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterWatchingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faceitmate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faceitmate_proto_goTypes,
		DependencyIndexes: file_faceitmate_proto_depIdxs,
		EnumInfos:         file_faceitmate_proto_enumTypes,
		MessageInfos:      file_faceitmate_proto_msgTypes,
	}.Build()
	File_faceitmate_proto = out.File
	file_faceitmate_proto_rawDesc = nil
	file_faceitmate_proto_goTypes = nil
	file_faceitmate_proto_depIdxs = nil
}
